name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: swift test --xunit-output output.xml --parallel
