name: Test

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: swift test --xunit-output output.xml --parallel
    - name: Upload test results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: output*.xml

  parse_result:
    runs-on: ubuntu-latest
    needs: test
    if: success() || failure()
    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: test-results
    - name: Publish Test Report
      id: publish-test-report
      uses: mikepenz/action-junit-report@v5
      with:
        report_paths: '**/*.xml'
        detailed_summary: true
        flaky_summary: true
    - name: Check outputs
      run: |
        echo "total: ${{ steps.publish-test-report.outputs.total }}"
        echo "passed: ${{ steps.publish-test-report.outputs.passed }}"
        echo "skipped: ${{ steps.publish-test-report.outputs.skipped }}"
        echo "retried: ${{ steps.publish-test-report.outputs.retried }}"
        echo "failed: ${{ steps.publish-test-report.outputs.failed }}"
        echo "summary: ${{ steps.publish-test-report.outputs.summary }}"
        echo "detailed_summary: ${{ steps.publish-test-report.outputs.detailed_summary }}"
        echo "flaky_summary: ${{ steps.publish-test-report.outputs.flaky_summary }}"
    - name: Parse HTML
      id: parse-html
      run: |
        cargo install htmlq
        result=`echo "${{ steps.publish-test-report.outputs.detailed_summary }}" | htmlq table tr td -t`
        echo $result >> failure_summary.txt
    - name: Echo failed result
      if: steps.parse-html.outputs.failed_result != ''
      run: |
        result=`cat failure_summary.txt`
        echo $result
